<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <CodeAnalysisRuleSet>..\..\stylecop.ruleset.xml</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FhirPseudonymizer\FhirPseudonymizer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\..\.stylecop.json" />
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
    <None
      Include="..\FhirPseudonymizer\anonymization.yaml;..\FhirPseudonymizer\hipaa-anonymization.yaml"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None Include="complex-anonymization.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None
      Include="..\FhirPseudonymizer.Tests\Fixtures\Data\Resources\Ashleigh_Olson_9d9b8bed-7b79-7fa9-cea1-f133a6b4d551.json"
      Link="Ashleigh_Olson_9d9b8bed-7b79-7fa9-cea1-f133a6b4d551.json"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
