services:
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.60@sha256:4fd2d70fa347d6a47e79fcb06b1c177e6079f92cba88b083153d56263082135e
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1"
        reservations:
          memory: 1g
          cpus: "1"
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    ports:
      - "6831:6831/udp"
      - "127.0.0.1:16686:16686"

  vfps-db:
    image: docker.io/library/postgres:18.3@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"
        reservations:
          memory: 1g
          cpus: "1"
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      # kics-scan ignore-line
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vfps

  vfps:
    image: ghcr.io/miracum/vfps:v1.3.7@sha256:7e9392f57499ed5b50aacdf3960f2ca126d3b5bfb5a35989d28ba21ccb3b52c0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "2"
        reservations:
          memory: 512m
          cpus: "2"
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    environment:
      COMPlus_EnableDiagnostics: "0"
      ForceRunDatabaseMigrations: "true"
      ConnectionStrings__PostgreSQL: "Host=vfps-db:5432;Database=vfps;Timeout=60;Max Auto Prepare=5;Application Name=vfps;Maximum Pool Size=50;"
      PGUSER: postgres
      # kics-scan ignore-line
      PGPASSWORD: postgres
      Tracing__IsEnabled: "true"
      Tracing__Jaeger__AgentHost: "jaeger"
      Pseudonymization__Caching__Namespaces__IsEnabled: "true"
    depends_on:
      - vfps-db
    ports:
      # Http1, Http2, Http3
      - "127.0.0.1:8080:8080"
      # Http2-only for plaintext gRPC
      - "127.0.0.1:8081:8081"

  gpas-entici-mock:
    image: docker.io/mockserver/mockserver:5.15.0@sha256:0f9ef78c94894ac3e70135d156193b25e23872575d58e2228344964273b4af6b
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1"
        reservations:
          memory: 512m
          cpus: "1"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
    ports:
      - 127.0.0.1:1080:1080
    volumes:
      - ./hack/mocks:/config:ro

  kafka:
    image: docker.io/apache/kafka:4.3.0@sha256:0be4c9eb3565733612d2836d65636fd611a219ebcf5b4162e5ac259ea0ecb907
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    environment:
      KAFKA_NODE_ID: "0"
      KAFKA_KRAFT_CLUSTER_ID: "kafka-fhir-to-server"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_PROCESS_ROLES: "controller,broker"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_MESSAGE_MAX_BYTES: "31457280"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LOG_CLEANUP_POLICY: compact
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    ports:
      - 127.0.0.1:9094:9094

  akhq:
    image: docker.io/tchiotludo/akhq:0.27.1@sha256:66a43e84a3355f0a13f3b165a48f515c72a5344ea7ea0575a3e4efe2d3ac9a91
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 127.0.0.1:8084:8080
    depends_on:
      - kafka

  mock-data-loader:
    image: docker.io/confluentinc/cp-kcat:8.2.2@sha256:66889260e24491424ea6066f63d6c091aa50b995a1a4cbfdd902322546d1e69e
    entrypoint: ["/bin/bash", "-c"]
    restart: on-failure
    command:
      [
        "while true; do kcat -b kafka:9092 -t fhir-msg -P -K: -l /data/fhir.ndjson; sleep 5; done",
      ]
    volumes:
      - ${PWD}/hack/fhir.ndjson:/data/fhir.ndjson:ro
    depends_on:
      - kafka

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4@sha256:0aae0de7fca85525f727d3354df17896092de8bb26ae4c12d89c77e5df8cbce4
    restart: unless-stopped
    profiles:
      - keycloak
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1"
        reservations:
          memory: 2g
          cpus: "1"
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      # kics-scan ignore-line
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        # /opt/keycloak/bin/kc.sh export --file /tmp/fhir-pseudonymizer-test-realm-export.json --realm fhir-pseudonymizer-test
        source: ./hack/keycloak/fhir-pseudonymizer-test-realm-export.json
        target: /opt/keycloak/data/import/fhir-pseudonymizer-test-realm-export.json
        read_only: true
    ports:
      - "127.0.0.1:8083:8080"
