services:
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.47@sha256:ac85f812596ffb596ddcdbfe7c287eb44f781706e4232741bf9f81ff23aa1da9
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1"
        reservations:
          memory: 1g
          cpus: "1"
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    ports:
      - "6831:6831/udp"
      - "127.0.0.1:16686:16686"

  vfps-db:
    image: docker.io/library/postgres:15.3@sha256:362a63cb1e864195ea2bc29b5066bdb222bc9a4461bfaff2418f63a06e56bce0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"
        reservations:
          memory: 1g
          cpus: "1"
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vfps

  vfps:
    image: ghcr.io/miracum/vfps:v1.3.0@sha256:16d723600764eeebb49c88c4bfdf2bd7f84e3d5f9602c25b307bf52cf50e7e37
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "2"
        reservations:
          memory: 512m
          cpus: "2"
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    environment:
      COMPlus_EnableDiagnostics: "0"
      ForceRunDatabaseMigrations: "true"
      ConnectionStrings__PostgreSQL: "Host=vfps-db:5432;Database=vfps;Timeout=60;Max Auto Prepare=5;Application Name=vfps;Maximum Pool Size=50;"
      PGUSER: postgres
      PGPASSWORD: postgres
      Tracing__IsEnabled: "true"
      Tracing__Jaeger__AgentHost: "jaeger"
      Pseudonymization__Caching__Namespaces__IsEnabled: "true"
    depends_on:
      - vfps-db
    ports:
      # Http1, Http2, Http3
      - "127.0.0.1:8080:8080"
      # Http2-only for plaintext gRPC
      - "127.0.0.1:8081:8081"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1@sha256:4d74df855d11725ea5020b5329c94837254cd72af44fd6afeb7668672e8fb460
    restart: unless-stopped
    profiles:
      - keycloak
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1"
        reservations:
          memory: 2g
          cpus: "1"
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        # /opt/keycloak/bin/kc.sh export --file /tmp/fhir-pseudonymizer-test-realm-export.json --realm fhir-pseudonymizer-test
        source: ./hack/keycloak/fhir-pseudonymizer-test-realm-export.json
        target: /opt/keycloak/data/import/fhir-pseudonymizer-test-realm-export.json
        read_only: true
    ports:
      - "127.0.0.1:8083:8080"
