name: playground

on:
  push:
    branches: [master]
  release:
    types: [created]
  pull_request:
    branches: [master]
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    name: build
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: "10.0.x"

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Publish
        run: dotnet publish src/FhirPseudonymizer.Playground/FhirPseudonymizer.Playground.csproj -c Release -o publish-output

      - name: Move output under /playground
        run: |
          mkdir -p pages-root/playground
          cp -r publish-output/wwwroot/. pages-root/playground/

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: pages-root

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    name: deploy
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
